### PR TITLE
Milestone five : Styling the app with the required instructions

### PR DESCRIPTION
**Pull request by moudio**
In this pull request, I styled the app with the required instructions found on Zeplin.

### CODE REVIEW

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Hi! Looking great so far, but not completely as it should.

Could you please work on the following improvements:

* [ ] Try to make the header resemble the original one:

image

Versus

image

* [ ] Add some padding on the sides to your inputs so there is some white space between the border of the input and the text inside it:

image

Versus 

image

Status: __Request changes__.

**Comment by uche-inyama** [comment]
Hi TSE :wave: 


We have implemented the changes requested from TSE, MauricioRobayo

- Added Books, categories and an avatar on the navigation bar.
- Added padding on *```Add new book```*, input element.

Best, 

Henry & Diouf.

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Thank you, team, for implementing the changes! It's looking much better now according to the specs.

But a new issue came up, the form at the bottom for creating a new book should be align with the rest of the content:

image

Versus

image

And really sorry because I was not explicit about this before, but try to place your categories filter on the header that you have now created. You can replace the categories tab that is showing on the specs with your category filter if you can make it look something like this:

image

Status: __Request changes__.

Optional: I didn't notice before so I'm making this an optional change, but the category should be above the title of the book according to the specs given, not below.

image

We want this to look the best possible! You are almost there, congratulations for making it this far on the program!

**Comment by uche-inyama** [comment]
Hi TSE :wave: 

We have made the changes including the optional requirement recommended by TSE, MauricioRobayo, which are:

- Adjusting the form to align with the rest of the content.
- Adding categories to the navigation bar.
- Adjusting the category of the book, to be above the title of the book. [**optional requirement**]

Best,

@Team - Henry & Diouf :slightly_smiling_face:

**Review by shloch — APPROVED** [review]
### yayyyyy we're good to goooooo

accomplished

**Pull request merged**
